class WakeModel:
    """
    Calculates the aerodynamic wake generated by the car ahead.

    This model intentionally starts simple and will later become
    season-aware, speed-aware and eventually corner-aware.

    All wake-related calculations should live here.
    """

    ##############################################################

    FULL_WAKE_DISTANCE = 40.0
    MEDIUM_WAKE_DISTANCE = 80.0
    LIGHT_WAKE_DISTANCE = 120.0
    MAX_WAKE_DISTANCE = 180.0

    ##############################################################

    def dirty_air_weight(
        self,
        gap_distance: float | None,
    ) -> float:

        if gap_distance is None:
            return 0.0

        if gap_distance <= self.FULL_WAKE_DISTANCE:
            return 1.00

        if gap_distance <= self.MEDIUM_WAKE_DISTANCE:
            return 0.80

        if gap_distance <= self.LIGHT_WAKE_DISTANCE:
            return 0.50

        if gap_distance <= self.MAX_WAKE_DISTANCE:
            return 0.20

        return 0.0

    ##############################################################

    def is_dirty_air(
        self,
        gap_distance: float | None,
    ) -> bool:

        return (
            self.dirty_air_weight(gap_distance)
            > 0.0
        )