from .wake_profiles import WakeProfile
from .models import WakeAnalysis


class WakeModel:

    """
    Calculates the aerodynamic wake generated by the car ahead.

    This model intentionally starts simple and will later become
    season-aware, speed-aware and eventually corner-aware.

    All wake-related calculations should live here.
    """

    ##############################################################

    MIN_WAKE_SPEED = 60.0
    MAX_WAKE_SPEED = 300.0

    ##############################################################

    def __init__(
        self,
        profile: WakeProfile,
    ):
        self.profile = profile

    ##############################################################

    def analyze(
        self,
        gap_distance: float |None,
        speed: float | None,
        drs: int | None,
    ) -> WakeAnalysis:

        ##########################################################
        # No car ahead
        ##########################################################

        if gap_distance is None:

            return WakeAnalysis(

                profile=self.profile.name,

                distance_weight=0.0,

                speed_factor=1.0,

                drs_factor=1.0,

                final_weight=0.0,

                in_dirty_air=False,

                gap_distance=None,
            )

        ##########################################################
        # Distance effect
        ##########################################################

        if gap_distance <= self.profile.full_distance:

            distance_weight = self.profile.full_weight

        elif gap_distance <= self.profile.medium_distance:

            distance_weight = self._interpolate(

                gap_distance,

                self.profile.full_distance,
                self.profile.medium_distance,

                self.profile.full_weight,
                self.profile.medium_weight,
            )

        elif gap_distance <= self.profile.light_distance:

            distance_weight = self._interpolate(

                gap_distance,

                self.profile.medium_distance,
                self.profile.light_distance,

                self.profile.medium_weight,
                self.profile.light_weight,
            )

        elif gap_distance <= self.profile.maximum_distance:

            distance_weight = self._interpolate(

                gap_distance,

                self.profile.light_distance,
                self.profile.maximum_distance,

                self.profile.light_weight,
                self.profile.maximum_weight,
            )

        else:

            distance_weight = 0.0

        ##########################################################
        # Speed effect
        ##########################################################

        speed_factor = self._speed_factor(
            speed
        )

        ##########################################################
        # DRS effect
        ##########################################################

        drs_factor = self._drs_factor(
            drs
        )

        ##########################################################

        final_weight = (

            distance_weight
            * speed_factor
            * drs_factor

        )

        ##########################################################

        return WakeAnalysis(

            profile=self.profile.name,

            distance_weight=distance_weight,

            speed_factor=speed_factor,

            drs_factor=drs_factor,

            final_weight=final_weight,

            in_dirty_air=(
                final_weight > 0.0
            ),

            gap_distance=gap_distance,
        )

    ##############################################################

    def dirty_air_weight(
        self,
        gap_distance: float | None,
        speed: float | None,
        drs: int | None,
    ) -> float:

        return self.analyze(

            gap_distance,
            speed,
            drs,

        ).final_weight

    ##############################################################

    def is_dirty_air(
        self,
        gap_distance: float | None,
        speed: float | None,
        drs: int | None,
    ) -> bool:

        return self.analyze(

            gap_distance,
            speed,
            drs,

        ).in_dirty_air

    ##############################################################

    def _interpolate(
        self,
        value: float,
        x1: float,
        x2: float,
        y1: float,
        y2: float,
    ) -> float:

        if value <= x1:
            return y1

        if value >= x2:
            return y2

        fraction = (

            value - x1

        ) / (

            x2 - x1

        )

        return (

            y1
            + fraction * (y2 - y1)

        )

    ##############################################################

    def _speed_factor(
        self,
        speed: float | None,
    ) -> float:

        if speed is None:
            return 1.0

        ##########################################################
        # Very low speed
        ##########################################################

        if speed <= 60:
            return 0.15

        ##########################################################
        # Low speed
        ##########################################################

        if speed <= 100:
            return 0.35

        ##########################################################
        # Medium speed
        ##########################################################

        if speed <= 150:
            return 0.60

        ##########################################################
        # Fast corners
        ##########################################################

        if speed <= 220:
            return 0.85

        ##########################################################
        # High speed
        ##########################################################

        return 1.00

    ##############################################################

    def _drs_factor(
        self,
        drs: int | None,
    ) -> float:

        if drs is None:
            return 1.0

        ##########################################################
        # DRS flap open
        ##########################################################

        if drs >= 10:
            return self.profile.drs_modifier

        return 1.0